---
# web server installation
- hosts: webserver
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present
    - name: start apache
      service:
        name: httpd
        state: started
#database installation
- hosts: database
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install postgresql
      yum:
        name: postgresql
        state: present
