servers = {
  "ServerA" => { :ip => "192.168.56.2", :cpus => 1, :mem => 1024 },
  "ServerB" => { :ip => "192.168.56.3", :cpus => 1, :mem => 1024 }
}
Vagrant.configure("2") do |config|
  servers.each_with_index do |(hostname, info), index|
     config.vm.define hostname do |cfg|
       cfg.vm.provider :virtualbox do |vb, override| 
         config.vm.box = "generic/centos7"
         override.vm.network "private_network", ip: "#{info[:ip]}"
         override.vm.hostname = hostname
         vb.name = hostname
       end
     end
  end
end